// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_petchbumpen_register/test/integration/backup_service_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_petchbumpen_register/models/backup_settings.dart'
    as _i8;
import 'package:flutter_petchbumpen_register/services/auto_backup_service.dart'
    as _i7;
import 'package:flutter_petchbumpen_register/services/file_management_service.dart'
    as _i10;
import 'package:flutter_petchbumpen_register/services/json_export_service.dart'
    as _i2;
import 'package:flutter_petchbumpen_register/services/restore_service.dart'
    as _i9;
import 'package:flutter_petchbumpen_register/services/sql_export_service.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:sqflite/sqflite.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JsonExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockJsonExportService extends _i1.Mock implements _i2.JsonExportService {
  MockJsonExportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> exportAllTablesToJson() =>
      (super.noSuchMethod(
            Invocation.method(#exportAllTablesToJson, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#exportAllTablesToJson, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<Map<String, dynamic>>> exportTableToJson(
    _i5.Database? database,
    String? tableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exportTableToJson, [database, tableName]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<String> saveJsonToFile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveJsonToFile, [data]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#saveJsonToFile, [data]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  String generateJsonFileName() =>
      (super.noSuchMethod(
            Invocation.method(#generateJsonFileName, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#generateJsonFileName, []),
            ),
          )
          as String);

  @override
  _i3.Future<List<String>> getJsonBackupFiles() =>
      (super.noSuchMethod(
            Invocation.method(#getJsonBackupFiles, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<int> getJsonFileSize(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#getJsonFileSize, [filePath]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<String, dynamic>?> readJsonBackupFile(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#readJsonBackupFile, [filePath]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}

/// A class which mocks [SqlExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSqlExportService extends _i1.Mock implements _i6.SqlExportService {
  MockSqlExportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> exportToSql() =>
      (super.noSuchMethod(
            Invocation.method(#exportToSql, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#exportToSql, [])),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> saveSqlToFile(String? sqlContent, String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#saveSqlToFile, [sqlContent, fileName]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#saveSqlToFile, [sqlContent, fileName]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  String generateDailyBackupFileName() =>
      (super.noSuchMethod(
            Invocation.method(#generateDailyBackupFileName, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#generateDailyBackupFileName, []),
            ),
          )
          as String);

  @override
  String generateTimestampedFileName() =>
      (super.noSuchMethod(
            Invocation.method(#generateTimestampedFileName, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#generateTimestampedFileName, []),
            ),
          )
          as String);

  @override
  _i3.Future<String> exportDailyBackup() =>
      (super.noSuchMethod(
            Invocation.method(#exportDailyBackup, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#exportDailyBackup, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> exportTimestampedBackup() =>
      (super.noSuchMethod(
            Invocation.method(#exportTimestampedBackup, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#exportTimestampedBackup, []),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [AutoBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutoBackupService extends _i1.Mock implements _i7.AutoBackupService {
  MockAutoBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> performDailyBackupIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#performDailyBackupIfNeeded, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> shouldPerformBackup(
    String? fileName,
    DateTime? targetDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shouldPerformBackup, [fileName, targetDate]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  String getDailyBackupFileName(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyBackupFileName, [date]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getDailyBackupFileName, [date]),
            ),
          )
          as String);

  @override
  _i3.Future<void> updateLastBackupTime(DateTime? backupTime) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastBackupTime, [backupTime]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> shouldScheduleAutoBackup(_i8.BackupSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#shouldScheduleAutoBackup, [settings]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> performAutoBackup(_i8.BackupSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#performAutoBackup, [settings]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<Map<String, dynamic>> getBackupStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getBackupStatus, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [RestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestoreService extends _i1.Mock implements _i9.RestoreService {
  MockRestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> restoreFromSqlFile(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromSqlFile, [filePath]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createEmergencyBackup() =>
      (super.noSuchMethod(
            Invocation.method(#createEmergencyBackup, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> validateBackupFile(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#validateBackupFile, [filePath]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> dropAllTables() =>
      (super.noSuchMethod(
            Invocation.method(#dropAllTables, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> executeSqlFile(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#executeSqlFile, [filePath]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> verifyRestoreIntegrity() =>
      (super.noSuchMethod(
            Invocation.method(#verifyRestoreIntegrity, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [FileManagementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileManagementService extends _i1.Mock
    implements _i10.FileManagementService {
  MockFileManagementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getBackupDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#getBackupDirectory, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getBackupDirectory, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> ensureBackupDirectoryExists() =>
      (super.noSuchMethod(
            Invocation.method(#ensureBackupDirectoryExists, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getBackupFiles() =>
      (super.noSuchMethod(
            Invocation.method(#getBackupFiles, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> deleteOldBackups({int? maxDays = 31}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldBackups, [], {#maxDays: maxDays}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> hasWritePermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasWritePermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> requestWritePermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestWritePermission, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getAvailableStorageSpace() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableStorageSpace, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<String> createBackupFile(String? fileName, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#createBackupFile, [fileName, content]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#createBackupFile, [fileName, content]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> backupFileExists(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#backupFileExists, [fileName]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getBackupFileSize(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getBackupFileSize, [fileName]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> deleteBackupFile(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBackupFile, [fileName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
